### ISSUE TITLE
Can you elaborate on the reason why UDP hole-punching is favored over TCP hole-punching.

### ISSUE THREAD

**Issue by xg590** [TudbuT/qft#11]
Hi Daniel, I did UDP hole punching before but failed to ensure the connection reliability for file transfer. Your work is really awesome.  Do you have experience on TCP hole-punching, which I never succeeded.

Another minor question: Regarding my personal setups, the bitrate cannot be higher than 1000. Otherwise, packets dropping becomes prominent. Can you provide more guidance about the bitrate in the documentation?

**Comment by TudbuT** [comment]
Hey there! The issue with the bitrate is that it directly translates to packet size, and many ISPs don't allow large packet sizes. 
I don't have much experience TCP hole-punching, primarily due to limitations in TCP APIs. I need to be able to re-use the same port multiple times, but I cannot do that with the TcpStream provided by rust, for example. Most languages seem to have this issue. 

If there was such a function, `bind` would make it totally possible to replace all usages of UdpSocket with TcpStream and have it work with minimal modifications.

I'd imagine something like this, if `bind` existed:
```rs
    let holepunch = TcpStream::bind(
        &bind_addr, 
        args.get(2).unwrap_or_else(|| ...)
    ).expect("unable to connect to helper");
```

instead of (taken directly from qft):
```rs
    let holepunch = UdpSocket::bind(&bind_addr).expect("unable to create socket");
    holepunch
        .connect(args.get(2).unwrap_or_else(|| {
            print_args(args);
            panic!("unreachable")
        }))
        .expect("unable to connect to helper");
```

The way I currently ensure a reliable connection is essentially by re-implementing some core parts of TCP but sending that over UDP.

**Comment by xg590** [comment]
Thanks for your comments.
